config/routes.rb
Rails.application.routes.draw do
  get 'admin_panel/new'
  get 'admin_panel/create'
  resources :favorite_shops
  resources :favorite_items
  resources :items
  resources :shops
  resources :admin_panel
  resources :admin_panel_unapprove
  resources :admin_panel_unsuspend
  root 'pages#home'
  devise_for :users


  resources :shops do
    put :add_to_favorite, on: :member
    put :set_approve, on: :member
    put :set_suspend, on: :member
    put :set_unsuspend, on: :member
  end
  resources :items do
    put :add_to_favorite, on: :member
  end
end

app/models/favorite_item.rb
class FavoriteItem < ApplicationRecord
  belongs_to :user
  belongs_to :item
end

app/controllers/favorite_items_controller.rb
class FavoriteItemsController < ApplicationController
  before_action :authenticate_user!, only: %i[index]

  # GET /favorite_items or /favorite_items.json
  def index
    @favorite_items = FavoriteItem.where(user_id: current_user.id)
  end


end

app/helpers/favorite_items_helper.rb
module FavoriteItemsHelper
end

app/views/favorite_items/_favorite_item.html.erb
<td><%= Item.where(id: favorite_item.item_id).first.id %></td>
<td><%= Item.where(id: favorite_item.item_id).first.name %></td>
<td><%= Item.where(id: favorite_item.item_id).first.stock %></td>
<td><%= Item.where(id: favorite_item.item_id).first.description %></td>
<td><%= Item.where(id: favorite_item.item_id).first.shop.name %></td>
<% if current_user.present? %>
  <% if !current_user.reload.item_favorites.include?(Item.where(id: favorite_item.item_id).first) %>
    <td><%= link_to "favorite",   add_to_favorite_item_path(Item.where(id: favorite_item.item_id).first, type: "favorite"), data: { "turbo-method": :put } %></td>
  <% else %>
    <td><%= link_to "unfavorite", add_to_favorite_item_path(Item.where(id: favorite_item.item_id).first, type: "unfavorite"), data: { "turbo-method": :put } %></td>
  <% end %>
<% end %>

app/views/favorite_items/_form.html.erb
<%= form_with(model: favorite_item) do |form| %>
  <% if favorite_item.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(favorite_item.errors.count, "error") %> prohibited this favorite_item from being saved:</h2>

      <ul>
        <% favorite_item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/favorite_items/edit.html.erb
<p style="color: green"><%= notice %></p>
<p style="color: red"><%= alert %></p>
<h1>Editing favorite item</h1>

<%= render "form", favorite_item: @favorite_item %>

<br>

<div>
  <%= link_to "Show this favorite item", @favorite_item %> |
  <%= link_to "Back to favorite items", favorite_items_path %>
</div>

app/views/favorite_items/index.html.erb
<p style="color: green"><%= notice %></p>
<p style="color: red"><%= alert %></p>

<h1>Favorite items</h1>

<div id="favorite_items">
  <table class="table table-striped">
    <thead class="thead-dark">
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Name</th>
      <th scope="col">Stock</th>
      <th scope="col">Description</th>
      <th scope="col">Shop Name</th>
      <% if current_user.present? %>
        <th scope="col">Add to Favorites</th>
      <% end %>
      <th scope="col">Show</th>
    </tr>
    </thead>
    <tbody>
    <% @favorite_items.each do |fav_item| %>
      <tr>
        <%= render fav_item %>

        <td><%= link_to 'Show', Item.where(id: fav_item.item_id).first %></td></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/favorite_items/new.html.erb
<p style="color: green"><%= notice %></p>
<p style="color: red"><%= alert %></p>
<h1>New favorite item</h1>

<%= render "form", favorite_item: @favorite_item %>

<br>

<div>
  <%= link_to "Back to favorite items", favorite_items_path %>
</div>

app/views/favorite_items/show.html.erb
<p style="color: green"><%= notice %></p>
<p style="color: red"><%= alert %></p>

<%= render @favorite_item %>

<div>
  <%= link_to "Edit this favorite item", edit_favorite_item_path(@favorite_item) %> |
  <%= link_to "Back to favorite items", favorite_items_path %>

  <%= button_to "Destroy this favorite item", @favorite_item, method: :delete %>
</div>