config/routes.rb
Rails.application.routes.draw do
  get 'admin_panel/new'
  get 'admin_panel/create'
  resources :favorite_shops
  resources :favorite_items
  resources :items
  resources :shops
  resources :admin_panel
  resources :admin_panel_unapprove
  resources :admin_panel_unsuspend
  root 'pages#home'
  devise_for :users


  resources :shops do
    put :add_to_favorite, on: :member
    put :set_approve, on: :member
    put :set_suspend, on: :member
    put :set_unsuspend, on: :member
  end
  resources :items do
    put :add_to_favorite, on: :member
  end
end

app/models/shop.rb
class Shop < ApplicationRecord
  validates :name, :bio, presence: true
  validates :user_id, :name, uniqueness: true

  # Relationships
  belongs_to :user
  has_many :items, dependent: :destroy

  has_many :favorite_shops, dependent: :destroy
  has_many :shop_favorited_by, through: :favorite_shops, source: :user


end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :set_shop, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: %i[index show]
  before_action :user_has_shop?, only: %i[new create]
  before_action :user_is_owner?, only: %i[edit update destroy]
  # GET /shops or /shops.json

  def set_approve
    id = params[:id]
    @shop = Shop.find(id)
    @shop.isWaitingApproval = 0
    @shop.save
  end

  def set_suspend
    id = params[:id]
    @shop = Shop.find(id)
    @shop.isLive = 0
    @shop.save
  end

  def set_unsuspend
    id = params[:id]
    @shop = Shop.find(id)
    @shop.isLive = 1
    @shop.save
  end

  def add_to_favorite
    type = params[:type]
    id = params[:id]
    @shop = Shop.find(id)
    case type
    when 'favorite'
      current_user.shop_favorites << @shop

    when 'unfavorite'
      if current_user.shop_favorites.include?(@shop)
        current_user.shop_favorites.delete(@shop)
      end

    else
      # type code here
    end
  end


  def index
    @shops = Shop.all
  end

  # GET /shops/1 or /shops/1.json
  def show

  end

  # GET /shops/new
  def new
    @shop = Shop.new
  end

  # GET /shops/1/edit
  def edit
  end

  # POST /shops or /shops.json
  def create
    # WHY DOESN'T "@shop = Shop.new(shop_params)" WORK?
    # WHEN I MANUALLY TYPE {"name"=>"AAAAAA", "bio"=>"AAAA"} , IT WORKS :D
    # WHEN IT COMES INSIDE shop_params, IT DOESN'T WORK :DDDDDD
    # -- Update --
    # so it seems it was passed as a "ActionController::Parameters" object, not as a hash, on the newer rails versions
    # ActionController::Parameters.permit_all_parameters = true
    # I think this is disabled by default for sql injection prevention

    # Whenever I do a migration that edits columns, I guess have to add the new columns to these permitted params
    # so I don't think this is a scalable solution. However this is the suggested solution
    @shop = Shop.new(permitted_shop_params)
    @shop.user_id = current_user.id # by passing current_user.id here, it prevents the user from changing the user_id
    #                                 by editing the network packets
    @shop.isLive = true
    @shop.isWaitingApproval = true

    respond_to do |format|
      if @shop.save
        format.html { redirect_to shop_url(@shop), notice: 'Shop was successfully created.' }
        format.json { render :show, status: :created, location: @shop }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shops/1 or /shops/1.json
  def update
    respond_to do |format|
      if @shop.update(permitted_shop_params)
        format.html { redirect_to shop_url(@shop), notice: 'Shop was successfully updated.' }
        format.json { render :show, status: :ok, location: @shop }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shops/1 or /shops/1.json
  def destroy
    @shop.destroy

    respond_to do |format|
      format.html { redirect_to shops_url, notice: 'Shop was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def auth_to_create_shop?
    current_user.role
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_shop
    @shop = Shop.find(params[:id])
  end

  def user_has_shop?
    if !auth_to_create_shop?
      redirect_to shops_path, alert: 'You are plain user.'
    elsif
      current_user.shop.present?
      redirect_to shops_path, alert: 'You already have a shop.'
    else
      return true
    end
    false
  end

  def user_is_admin
    current_user.isAdmin
  end

  def user_is_owner?
    if current_user.id != @shop.user_id
      redirect_to shops_path, alert: 'You are not the owner of this shop.'
    else
      return true
    end
    false
  end

  # Only allow a list of trusted parameters through.
  def shop_params
    params.fetch(:shop, {})
  end

  # Edit when new columns come in
  def permitted_shop_params
    params.fetch(:shop, {}).permit(:name, :bio)
  end
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/shops/_form.html.erb
<%= form_with(model: shop) do |form| %>
  <% if shop.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(shop.errors.count, "error") %> prohibited this shop from being saved:</h2>

      <ul>
        <% shop.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name %>:
    <%= form.text_field :name %>
    <br />
    <%= form.label :bio %>:
    <%= form.text_field :bio %>

    <br/>
    <%= form.submit %>

  </div>
<% end %>

app/views/shops/_shop.html.erb
<% if !shop.isWaitingApproval && shop.isLive%>
    <div class="card m-5" style="max-width: 15vw; min-width: 15vw">
  <img src="../ege.jpg" class="card-img-top" alt="...">
  <div class="card-body">
    <h4 class="card-text"><%= shop.name %></h4>
    <p class="card-text"><%= shop.bio %></p>
    <% if current_user.present? %>
      <% if !current_user.reload.shop_favorites.include?(shop) %>
        <p class="card-text"><small class="text-muted"><%= link_to "Add to Favorite",   add_to_favorite_shop_path(shop, type: "favorite"), data: { "turbo-method": :put } %></small></p>
      <% else %>
        <p class="card-text"><small class="text-muted"><%= link_to "unfavorite", add_to_favorite_shop_path(shop, type: "unfavorite"), data: { "turbo-method": :put } %></small></p>
      <% end %>
    <% end %>
    <p class="card-text"><small class="text-muted"><%= link_to 'Show', shop %></small></p>
  </div>
</div>
<% end %>

app/views/shops/edit.html.erb
<p style="color: green"><%= notice %></p>
<p style="color: red"><%= alert %></p>
<h1>Editing shop</h1>

<%= render "form", shop: @shop %>

<br>

<div>
  <%= link_to "Show this shop", @shop %> |
  <%= link_to "Back to shops", shops_path %>
</div>

app/views/shops/index.html.erb
<p style="color: green"><%= notice %></p>
<p style="color: red"><%= alert %></p>

<h1 class="text-center">Shops</h1>
<div class="card-group">
  <% @shops.each do |shop| %>
    <%= render shop %>
  <% end %>
</div>

app/views/shops/new.html.erb
<p style="color: green"><%= notice %></p>
<p style="color: red"><%= alert %></p>
<h1>New shop</h1>


<%= render "form", shop: @shop %>
<br>

<div>
  <%= link_to "Back to shops", shops_path %>
</div>

app/views/shops/show.html.erb
<p style="color: green"><%= notice %></p>
<p style="color: red"><%= alert %></p>

<div class="container">
<%= render @shop %>
  <% if current_user and current_user.id == @shop.user_id%>
    <%= link_to "Edit this shop", edit_shop_path(@shop), :class=>"btn btn-primary btn-lg" %>
    <%= button_to "Destroy this shop", @shop, method: :delete, :class=>"btn btn-danger btn-lg" %>
  <% end %>
  <%= link_to "Back to shops", shops_path, :class=>"btn btn-secondary btn-lg" %>
</div>