config/routes.rb
Rails.application.routes.draw do
  get 'admin_panel/new'
  get 'admin_panel/create'
  resources :favorite_shops
  resources :favorite_items
  resources :items
  resources :shops
  resources :admin_panel
  resources :admin_panel_unapprove
  resources :admin_panel_unsuspend
  root 'pages#home'
  devise_for :users


  resources :shops do
    put :add_to_favorite, on: :member
    put :set_approve, on: :member
    put :set_suspend, on: :member
    put :set_unsuspend, on: :member
  end
  resources :items do
    put :add_to_favorite, on: :member
  end
end

app/models/favorite_shop.rb
class FavoriteShop < ApplicationRecord
  belongs_to :user
  belongs_to :shop
end

app/controllers/favorite_shops_controller.rb
class FavoriteShopsController < ApplicationController
  before_action :authenticate_user!, only: %i[index]

  # GET /favorite_shops or /favorite_shops.json
  def index
    @favorite_shops = FavoriteShop.where(user_id: current_user.id)
  end
end

app/helpers/favorite_shops_helper.rb
module FavoriteShopsHelper
end

app/views/favorite_shops/_favorite_shop.html.erb
<% @shop = Shop.where(id: favorite_shop.shop_id).first %>

<div class="card m-5" style="max-width: 20vw; min-width: 15vw">
  <img src="ege.jpg" class="card-img-top" alt="...">
  <div class="card-body">
    <h4 class="card-text"><%= @shop.name %></h4>
    <p class="card-text"><%= @shop.bio %></p>
    <% if current_user.present? %>
      <% if !current_user.reload.shop_favorites.include?(@shop) %>
        <p class="card-text"><small class="text-muted"><%= link_to "Add to Favorite",   add_to_favorite_shop_path(@shop, type: "favorite"), data: { "turbo-method": :put } %></small></p>
      <% else %>
        <p class="card-text"><small class="text-muted"><%= link_to "unfavorite", add_to_favorite_shop_path(@shop, type: "unfavorite"), data: { "turbo-method": :put } %></small></p>
      <% end %>
    <% end %>
    <p class="card-text"><small class="text-muted"><%= link_to 'Show', @shop %></small></p>
  </div>
</div>

app/views/favorite_shops/_form.html.erb
<%= form_with(model: favorite_shop) do |form| %>
  <% if favorite_shop.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(favorite_shop.errors.count, "error") %> prohibited this favorite_shop from being saved:</h2>

      <ul>
        <% favorite_shop.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/favorite_shops/edit.html.erb
<p style="color: green"><%= notice %></p>
<p style="color: red"><%= alert %></p>
<h1>Editing favorite shop</h1>

<%= render "form", favorite_shop: @favorite_shop %>

<br>

<div>
  <%= link_to "Show this favorite shop", @favorite_shop %> |
  <%= link_to "Back to favorite shops", favorite_shops_path %>
</div>

app/views/favorite_shops/index.html.erb
<p style="color: green"><%= notice %></p>
<p style="color: red"><%= alert %></p>

<h1 class="text-center" >Favorite shops</h1>


<div id="favorite_shops">

    <% @favorite_shops.each do |fav_shop| %>

        <%= render fav_shop %>

        <%= link_to 'Show', Shop.where(id: fav_shop.shop_id).first %>

    <% end %>
</div>

app/views/favorite_shops/new.html.erb
<p style="color: green"><%= notice %></p>
<p style="color: red"><%= alert %></p>
<h1>New favorite shop</h1>

<%= render "form", favorite_shop: @favorite_shop %>

<br>

<div>
  <%= link_to "Back to favorite shops", favorite_shops_path %>
</div>

app/views/favorite_shops/show.html.erb
<p style="color: green"><%= notice %></p>
<p style="color: red"><%= alert %></p>

<%= render @favorite_shop %>

<div>
  <%= link_to "Edit this favorite shop", edit_favorite_shop_path(@favorite_shop) %> |
  <%= link_to "Back to favorite shops", favorite_shops_path %>

  <%= button_to "Destroy this favorite shop", @favorite_shop, method: :delete %>
</div>