config/routes.rb
Rails.application.routes.draw do
  get 'admin_panel/new'
  get 'admin_panel/create'
  resources :favorite_shops
  resources :favorite_items
  resources :items
  resources :shops
  resources :admin_panel
  resources :admin_panel_unapprove
  resources :admin_panel_unsuspend
  root 'pages#home'
  devise_for :users


  resources :shops do
    put :add_to_favorite, on: :member
    put :set_approve, on: :member
    put :set_suspend, on: :member
    put :set_unsuspend, on: :member
  end
  resources :items do
    put :add_to_favorite, on: :member
  end
end

app/views/layouts/_footer.html.erb
<div class="d-flex flex-column" style="min-height: 100vh">
  <!-- Footer -->
  <footer
    class="text-center text-lg-start text-dark mt-auto"
    style="background-color: #ECEFF1"
  >
    <section class="">
      <div class="container text-center text-md-start mt-5">
        <!-- Grid row -->
        <div class="row mt-3">
          <!-- Grid column -->
          <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
            <!-- Content -->
            <h6 class="text-uppercase fw-bold">Pickles</h6>
            <hr
              class="mb-4 mt-0 d-inline-block mx-auto"
              style="width: 60px; background-color: #7c4dff; height: 2px"
              />
            <p>
              Pickles Official Website
            </p>
          </div>
          <!-- Grid column -->

          <!-- Grid column -->
          <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
            <!-- Links -->
            <h6 class="text-uppercase fw-bold">Items</h6>
            <hr
              class="mb-4 mt-0 d-inline-block mx-auto"
              style="width: 60px; background-color: #7c4dff; height: 2px"
              />
            <p>
              <a href="#!" class="text-dark">Add Item</a>
            </p>
            <p>
              <a href="#!" class="text-dark">See Items</a>
            </p>
          </div>
          <!-- Grid column -->

          <!-- Grid column -->
          <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
            <!-- Links -->
            <h6 class="text-uppercase fw-bold">Shops</h6>
            <hr
              class="mb-4 mt-0 d-inline-block mx-auto"
              style="width: 60px; background-color: #7c4dff; height: 2px"
              />
            <p>
              <a href="#!" class="text-dark">Create Shop</a>
            </p>
            <p>
              <a href="#!" class="text-dark">See Shops</a>
            </p>
          </div>
          <!-- Grid column -->

          <!-- Grid column -->
          <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
            <!-- Links -->
            <h6 class="text-uppercase fw-bold">Contact</h6>
            <hr
              class="mb-4 mt-0 d-inline-block mx-auto"
              style="width: 60px; background-color: #7c4dff; height: 2px"
              />
            <p><i class="fas fa-home mr-3"></i> Istanbul, Turkey </p>
            <p><i class="fas fa-envelope mr-3"></i> info@pickles.com</p>
            <p><i class="fas fa-phone mr-3"></i> +90 216 216 5151</p>
          </div>
          <!-- Grid column -->
        </div>
        <!-- Grid row -->
      </div>
    </section>
    <!-- Section: Links  -->

    <!-- Copyright -->
    <div
      class="text-center p-3"
      style="background-color: rgba(0, 0, 0, 0.2)"
    >
      © 2022 Copyright:
      <h5 class="text-dark">pickles.com</h5
      >
    </div>
    <!-- Copyright -->
  </footer>
  <!-- Footer -->
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%=link_to root_path, class: 'navbar-brand' do %>
      <img src="http://127.0.0.1:3000/pickleshome.png" class="card-img-top" alt="..." style="min-width: 5vw; max-height: 3vw">
    <%end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Shops', shops_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Items', items_path, class: 'nav-link' %>
        </li>
        <% if current_user.present? %>
          <li class="nav-item">
            <%= link_to 'Favorites Shops', favorite_shops_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Favorite Items', favorite_items_path, class: 'nav-link' %>
          </li>
          <% if current_user.shop.present? %>
            <li class="nav-item">
              <%= link_to 'Create Item', new_item_path, class: 'nav-link' %>
            </li>
          <% elsif current_user.role %>
            <li class="nav-item">
              <%= link_to 'Create Shop', new_shop_path, class: 'nav-link' %>
            </li>
          <% end %>
          <% else %>
          <li class="nav-item">
              <%= link_to 'Sign Up', new_user_registration_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Sign In', new_user_session_path, class: 'nav-link' %>
            </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pickles</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body style="background-image: url('https://mdbootstrap.com/img/Photos/Others/images/76.jpg'); height: 100vh">
  <%= render "layouts/header" %>

    <div class="container">
      <br/>
      <%= yield %>
    </div>

  <%= render "layouts/footer" %>
  </body>

</html>